[programs.localnet]
timelock = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
timelock = "GutMKXfaxeoi8yg6UymENGm8BRTZ9RU3RSRLoJuCFaH8"
[programs.mainnet]
timelock = "8e72pYCDaxu3GqMfeQ5r8wFgoZSYk6oua1Qo9XpsZjX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "tests/test-wallet.json"

[scripts]
test = "mocha -t 1000000 tests/"
